### ISSUE TITLE
Generators Failing 

### ISSUE THREAD

**Issue by seanlaw** [takemaru/graphillion#36]
According to [PEP479](https://www.python.org/dev/peps/pep-0479/), you'll have to update your generators for compatibility with the latest versions of Python 3.7. Otherwise, users will get an error like:

    Traceback (most recent call last):
      File "./dxz.py", line 116, in <module>
        for sol in dxz.solutions:
      File "./dxz.py", line 45, in solutions
        for x in iter(self.zdd):
      File "/home/miniconda3/lib/python3.7/site-packages/graphillion/graphset.py", line 653, in __iter__
        for g in self._ss.__iter__():
    RuntimeError: generator raised StopIteration

**Comment by takemaru** [comment]
I've merged it and updated Graphillion.
